### PR TITLE
Fix multiple names test

### LINKED ISSUE #251: Test case usual_cli::multiple_names sorts expected value incorrectly on some file systems
It looks like the test case `usual_cli::multiple_names()` is failing on aarch64-linux devices. See this log: https://logs.ofborg.org/?attempt_id=ea8d0c05-ebcb-4177-bf7a-b618bd8f8ff8&key=nixos%2Fnixpkgs.280371

Unfortunately, I don't have an AArch64 device capable of compiling the project and can't reproduce this myself.

What's interesting to me is that the actual value seems to be the correct (sorted) output, whereas the expected value seems to be in the wrong order.

### PR DESCRIPTION
**Pull request by peret**
Fix #251

### CODE REVIEW

File: tests/_utils.rs [hunk 1]
```diff
@@ -79,7 +79,7 @@ impl Default for SampleWorkspace {
                 "0" => file!("")
                 "1" => file!("a")
                 "2" => file!("ab")
-                "3" => file!("abc")
+                "3" => file!("abcd")
```
Comment (KSXGitHub) [inline tests/_utils.rs]: Let's make multiply these by an order of 1000. For example

```rust
      "3" => file!("a".repeat(3000))
```

This should be enough to avoid similar problems in other filesystems.

**Review by KSXGitHub — CHANGES_REQUESTED** [review]

**Comment by KSXGitHub** [comment]
Thank you for your contribution.

File: tests/usual_cli.rs [hunk 2]
```diff
@@ -617,16 +617,17 @@ fn multiple_names() {
...
         .pipe(|children| {
-            DataTree::dir(
+            let mut data_tree = DataTree::dir(
                 OsStringDisplay::os_string_from("(total)"),
                 0.into(),
                 children.collect(),
-            )
+            );
+            data_tree.par_sort_by(|left, right| left.data().cmp(&right.data()).reverse());
+            data_tree
```
Comment (KSXGitHub) [inline tests/usual_cli.rs]: You can use `into_par_sorted`:

```rust
        .pipe(|children| {
            DataTree::dir(
                OsStringDisplay::os_string_from("(total)"),
                0.into(),
                children.collect(),
            )
        })
        .pipe(|tree| tree.into_par_sorted(|left, right| left.data().cmp(&right.data()).reverse()));
```

File: tests/_utils.rs (hunk 1 above)
Comment (peret) [reply tests/_utils.rs]: Your suggested code actually resulted in a compilation error. I was able to make it work using the compiler's hints, but I'm not sure the result is ideal, since I don't know much Rust yet :D

File: tests/_utils.rs [hunk 3]
```diff
@@ -73,13 +73,14 @@ impl Default for SampleWorkspace {
...
         let temp = Temp::new_dir().expect("create working directory for sample workspace");
+        let long_str = "a".repeat(1000);
 
         MergeableFileSystemTree::<&str, &str>::from(dir! {
             "flat" => dir! {
                 "0" => file!("")
                 "1" => file!("a")
                 "2" => file!("ab")
-                "3" => file!("abcd")
+                "3" => file!(&*long_str)
```
Comment (KSXGitHub) [inline tests/_utils.rs]: Can you apply this change to ALL of them? `"0"` remains `""`, but `"1"` should be `"a".repeat(1000)` and `"2"` should be `"a".repeat(2)`. Do this for `nested/0/1` also (`"a".repeat(6000)`).

File: tests/_utils.rs [hunk 4]
```diff
@@ -73,13 +73,14 @@ impl Default for SampleWorkspace {
     /// Set up a temporary directory for tests.
     fn default() -> Self {
         let temp = Temp::new_dir().expect("create working directory for sample workspace");
+        let long_str = "a".repeat(1000);
```
Comment (KSXGitHub) [inline tests/_utils.rs]: Instead of declaring this variable, you can change the type of the tree instead:

```rust
MergeableFileSystemTree::<&str, String>::from(dir! {
```

File: tests/usual_cli.rs [hunk 5]
```diff
@@ -621,14 +621,13 @@ fn multiple_names() {
...
                 OsStringDisplay::os_string_from("(total)"),
                 0.into(),
                 children.collect(),
-            );
-            data_tree.par_sort_by(|left, right| left.data().cmp(&right.data()).reverse());
-            data_tree
-        });
+            )
+        })
+        .pipe(|tree| tree.into_par_sorted(|left, right| left.data().cmp(&right.data()).reverse()));
```
Comment (KSXGitHub) [inline tests/usual_cli.rs]: Usually, this would fail `cargo fmt`. Did you run `cargo fmt`?

**Review by KSXGitHub — CHANGES_REQUESTED** [review]

**Comment by KSXGitHub** [comment]
@a-n-n-a-l-e-e Since you have a machine capable of reproducing the test failure, can you try running the test in this PR?

**Review by KSXGitHub — APPROVED** [review]
Now I will wait for @a-n-n-a-l-e-e to response before merging this.

**Comment by peret** [comment]
I forgot to mention that I ended up finding a machine to reproduce this on as well. A server I rent uses XFS and the test failed on that machine every time. I confirmed there, that my fix is working.

**Review by peret — COMMENTED** [review]
Wait... the point of my original change in `tests/_utils.rs` was to make flat/ and nested/ have different sizes, so the original fault in the test case gets triggered. Now you changed it back so both folders are the same size again. It now gets reported as about 6k bytes instead of 6 bytes, but they're the same size again.

The fix is still working, but to me it doesn't make sense to just multiply everything by 1000. It doesn't change the situation :sweat_smile:

File: tests/_utils.rs [hunk 6]
```diff
@@ -74,16 +74,16 @@ impl Default for SampleWorkspace {
...
-                "2" => file!("ab")
-                "3" => file!("abc")
+                "1" => file!("a".repeat(1000))
+                "2" => file!("a".repeat(2000))
+                "3" => file!("a".repeat(3000))
             }
             "nested" => dir! {
                 "0" => dir! {
-                    "1" => file!("abcdef")
+                    "1" => file!("a".repeat(6000))
```
Comment (KSXGitHub) [inline tests/_utils.rs]: @peret 

> Wait... the point of my original change in `tests/_utils.rs` was to make flat/ and nested/ have different sizes, so the original fault in the test case gets triggered. Now you changed it back so both folders are the same size again. It now gets reported as about 6k bytes instead of 6 bytes, but they're the same size again.

Can you try apply this change locally to see if it still passes?

```suggestion
                    "1" => file!("a".repeat(5000))
```

**Comment by KSXGitHub** [comment]
@peret Also, can you try running the test in https://github.com/KSXGitHub/parallel-disk-usage/pull/253? I suspect it was because I didn't sort it more comprehensively.

File: tests/_utils.rs (hunk 6 above)
Comment (peret) [reply tests/_utils.rs]: @KSXGitHub 
Yes, that works and it still passes.

Comment (KSXGitHub) [reply tests/_utils.rs]: I think the reason why it still passes with 6000 was because directories have apparent size greater than zero. And `nested/0` is 2 directories compared to 1 directory of `flat`. So if you run the test with output printed out, so should see `nested` being place below `flat`. Can you test my hypothesis? I'm curious.

File: tests/usual_cli.rs [hunk 7]
```diff
@@ -627,7 +626,8 @@ fn multiple_names() {
                 0.into(),
                 children.collect(),
             )
-        });
+        })
+        .pipe(|tree| tree.into_par_sorted(|left, right| left.data().cmp(&right.data()).reverse()));
```
Comment (KSXGitHub) [inline tests/usual_cli.rs]:
```suggestion
        .into_par_sorted(|left, right| left.data().cmp(&right.data()).reverse());
```

**Comment by KSXGitHub** [comment]
The CI is deploying 0.9.1: https://github.com/KSXGitHub/parallel-disk-usage/actions/runs/7856824281
